kind: Deployment
apiVersion: apps/v1
metadata:
  name: customer
  namespace: dev-customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - image: markchen20190628/customer:v1.0
          name: customer
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: customer-port
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: customer
  namespace: dev-customer
spec:
  ports:
    - name: customer-port
      nodePort: 30003
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: customer
  type: NodePort